[package]
name = "cantools"
version = "0.1.0"
edition = "2021"
authors = ["Levi Feldman <levifeldman37@gmail.com>"]

[dependencies]
ic-cdk = "0.8.1"
rmp-serde = "1.1.1"
ic-stable-structures = "0.5.4"
serde = "1.0.164"
serde_bytes = "0.11.9"
